# This is a basic workflow to help you get started with Actions
name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v4
          with:
            BRANCH: gh-pages
            FOLDER: frontend
